// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk2IKA2vC_mZuQUVW6DU5SWF3r3Rwnaf4',
    appId: '1:78038618711:web:c86e69e95e0363d6a64912',
    messagingSenderId: '78038618711',
    projectId: 'learning-flutter-hiruka-93c59',
    authDomain: 'learning-flutter-hiruka-93c59.firebaseapp.com',
    storageBucket: 'learning-flutter-hiruka-93c59.firebasestorage.app',
    measurementId: 'G-T6FD41N8FB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIvuD1gGp1yzLDZojC_X-LmirTRxVxBM8',
    appId: '1:78038618711:android:1a1a449c2ab85eb7a64912',
    messagingSenderId: '78038618711',
    projectId: 'learning-flutter-hiruka-93c59',
    storageBucket: 'learning-flutter-hiruka-93c59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgrfP4fS2V4d1-UnatC_Qyvk1lPHXhrzk',
    appId: '1:78038618711:ios:178175d88cf48c8aa64912',
    messagingSenderId: '78038618711',
    projectId: 'learning-flutter-hiruka-93c59',
    storageBucket: 'learning-flutter-hiruka-93c59.firebasestorage.app',
    iosBundleId: 'com.example.learningflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgrfP4fS2V4d1-UnatC_Qyvk1lPHXhrzk',
    appId: '1:78038618711:ios:178175d88cf48c8aa64912',
    messagingSenderId: '78038618711',
    projectId: 'learning-flutter-hiruka-93c59',
    storageBucket: 'learning-flutter-hiruka-93c59.firebasestorage.app',
    iosBundleId: 'com.example.learningflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCk2IKA2vC_mZuQUVW6DU5SWF3r3Rwnaf4',
    appId: '1:78038618711:web:a924a2faf53b1730a64912',
    messagingSenderId: '78038618711',
    projectId: 'learning-flutter-hiruka-93c59',
    authDomain: 'learning-flutter-hiruka-93c59.firebaseapp.com',
    storageBucket: 'learning-flutter-hiruka-93c59.firebasestorage.app',
    measurementId: 'G-R5S7FRC2C1',
  );

}